package org.endeios.security.vaadin;

import java.util.List;
import java.util.UUID;

import org.endeios.security.domain.LogEntry;
import org.endeios.security.service.LogEntryService;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanContainer;
import com.vaadin.event.MouseEvents;
import com.vaadin.event.MouseEvents.ClickListener;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class SecWebAppMainWindow extends CustomComponent {

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Table table_1;
	@AutoGenerated
	private MenuBar menuBar_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button button_b;
	@AutoGenerated
	private Button button_a;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = -5504235251999428907L;
	private LogEntryService logEntryService;
	private ZoneListener zoneAListener;
	private ZoneListener zoneBListener;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public SecWebAppMainWindow(LogEntryService logEntryService) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		this.logEntryService = logEntryService;
		refreshTable();
		zoneAListener = new ZoneListener("A", logEntryService, this);
		zoneBListener = new ZoneListener("B", logEntryService, this);
//		label_1.addListener(MouseEvents.ClickEvent.class,zoneAListener,"handleAction");
//		label_2.addListener(MouseEvents.ClickEvent.class,zoneBListener,"handleAction");
		button_a.addListener((com.vaadin.ui.Button.ClickListener)zoneAListener);
		button_b.addListener((com.vaadin.ui.Button.ClickListener)zoneBListener);

	}

	/**
	 * @param logEntryService
	 */
	public void refreshTable() {
		List<LogEntry> data = this.logEntryService.getAllEntries();
		BeanContainer<UUID, LogEntry> bc = new BeanContainer<UUID, LogEntry>(
				LogEntry.class);
//		new SecWebAppMainWindow(logEntryService);
		bc.setBeanIdProperty("uuid");
		bc.addAll(data);
		table_1.setContainerDataSource(bc);
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, 0, 0);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		verticalLayout_1.addComponent(horizontalLayout_2);
		verticalLayout_1.setComponentAlignment(horizontalLayout_2,
				new Alignment(20));
		
		// menuBar_1
		menuBar_1 = new MenuBar();
		menuBar_1.setImmediate(false);
		menuBar_1.setWidth("100.0%");
		menuBar_1.setHeight("-1px");
		verticalLayout_1.addComponent(menuBar_1);
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("100.0%");
		verticalLayout_1.addComponent(table_1);
		verticalLayout_1.setExpandRatio(table_1, 1.0f);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("50.0%");
		horizontalLayout_2.setMargin(false);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Stanza A");
		horizontalLayout_2.addComponent(label_1);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Stanza B");
		horizontalLayout_2.addComponent(label_2);
		
		// button_a
		button_a = new Button();
		button_a.setCaption("Button");
		button_a.setImmediate(false);
		button_a.setWidth("-1px");
		button_a.setHeight("-1px");
		horizontalLayout_2.addComponent(button_a);
		
		// button_b
		button_b = new Button();
		button_b.setCaption("Button");
		button_b.setImmediate(false);
		button_b.setWidth("-1px");
		button_b.setHeight("-1px");
		horizontalLayout_2.addComponent(button_b);
		
		return horizontalLayout_2;
	}

}
